[package]
name = "monosecret_derive"
version = "0.3.3"
edition.workspace = true
license = "Apache-2.0"
repository = "https://github.com/ifiokjr/monosecret/tree/main/crates/monosecret_derive"
description = "Derive macros for Monosecret type-safe code generation"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
monosecret = { workspace = true, default-features = false }
proc-macro2.workspace = true
proc-macro2.default-features = true
quote.workspace = true
quote.default-features = true
serde.workspace = true
serde.default-features = true
syn.workspace = true
syn.default-features = true
toml.workspace = true
toml.default-features = true

[dev-dependencies]
http.workspace = true
http.default-features = true
insta.workspace = true
insta.default-features = true
monosecret.workspace = true
secrecy.workspace = true
secrecy.default-features = true
serde_json.workspace = true
serde_json.default-features = true
tempfile.workspace = true
tempfile.default-features = true
trybuild.workspace = true
trybuild.default-features = true
