[project]
name = "git-credentials"
revision = "1.0"
require_reason = false

[profiles.default]
USERNAME = { description = "Git username", required = false }
PASSWORD = { description = "Git password or token" }
