<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>

    <PackageId>Monosecret</PackageId>
    <Version>0.3.1</Version>
    <Authors>Ifiok Jr</Authors>
    <Description>C# SDK for Monosecret, the declarative secrets manager.</Description>
    <PackageTags>secrets;configuration;security;dotnet</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://ifiokjr.github.io/monosecret/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ifiokjr/monosecret</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="README.md" />
    <None Include="../../../../LICENSE" Pack="true" PackagePath="" />
    <None Include="runtimes/**" Pack="true"
          PackagePath="runtimes/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
